version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-dev
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - PORT=3000
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/productos
      - JWT_SECRET=Clave
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongo
      - redis
    command: npm run dev

  frontend:
    build:
      context: ./frontend-cromos
      dockerfile: Dockerfile
    container_name: frontend-dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend-cromos:/app
      - /app/node_modules
    depends_on:
      - backend

  mongo:
    image: mongo:6
    container_name: mongo-dev
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:alpine
    container_name: redis-dev
    ports:
      - "6379:6379"

volumes:
  mongo_data:
